apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: xmatuska-ambulance-webapi
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: xmatuska-ambulance-webapi
  filterTags:
    pattern: "main.*"
  policy:
    alphabetical:
      order: asc