apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: xmatuska-ambulance-ufe
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: xmatuska-ambulance-ufe
  filterTags:
      pattern: "main.*"
  policy:
    alphabetical:
      order: asc