apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xmatuska-cd
  namespace: wac-hospital
spec:
  interval: 42s
  wait: true
  path: clusters/localhost
  prune: true
  sourceRef:
    kind: GitRepository
    name: xmatuska-gitops-repo
  dependsOn:
    - name: xmatuska-local-prepare
