apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xmatuska-local-install
  namespace: wac-hospital
spec:
  interval: 120s
  wait: true
  force: true
  dependsOn:
    - name: xmatuska-local-prepare
  path: clusters/localhost/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: xmatuska-gitops-repo
