apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xmatuska-local-prepare
  namespace: wac-hospital
spec:
  interval: 120s
  wait: true
  path: clusters/localhost/prepare
  prune: true
  sourceRef:
    kind: GitRepository
    name: xmatuska-gitops-repo
