apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital
labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/xmatuska-ambulance-ufe
- ../../../apps/xmatuska-ambulance-webapi

#patches:
#- path: patches/ambulance-webapi.service.yaml

components:
- ../../../components/version-developers
- https://github.com/sprowk/xmatuska-webapi//deployments/kustomize/components/mongodb