apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmatuska-ambulance-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: xmatuska-ambulance-ufe-label
  template:
    metadata:
      labels: 
        pod: xmatuska-ambulance-ufe-label
    spec:
      containers:
      - name: ambulance-ufe-container
        image: sprowk/xmatuska-ufe:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:               
            memory: "32M"
            cpu: "0.1"
          limits:
            memory: "320M"
            cpu: "0.3"