apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xmatuska-ambulance-ufe-content
spec:
  microFrontend: xmatuska-ambulance-ufe
  element: xmatuska-ambulance-wl-app
  
  attributes:
    - name: base-path
      value: /xmatuska-ambulance-wl/
    - name: api-base
      value: http://localhost:5001/api
    - name: ambulance-id
      value: bobulova

  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xmatuska-ambulance-wl(/.*)?$"